######################################################################
# Automatically generated by qmake (3.0) Mon Oct 28 13:28:53 2019
######################################################################

TEMPLATE = app
TARGET = qtros
INCLUDEPATH += .

# Input
HEADERS += include/qtros/main_window.hpp include/qtros/qnode.hpp
FORMS += ui/main_window.ui
SOURCES += src/main.cpp src/main_window.cpp src/qnode.cpp
RESOURCES += resources/images.qrc
